### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by KashyapNadendla** [INFO526-DataViz/project-01-ScatterPlot-Sorcerers#1]
The following is the peer review of the project proposal by [R-tisans of Visuals]. The team members that participated in this review are 

- [Rahul Prakash Bangad] - [@rahulbangad98]
- [Athira Thekkemadathil Anilkumar] - @[AthiraThekkemadathilAnilkumar]
- [Visalakshi Prakash Iyer] - [@visalakshi2001]
- [Kashyap Sai Prasad Nadendla] - [@KashyapNadendla]

- Describe the goal of the project.

Presumed goal of the project is to study the relation between hotness of sauce and failure, as well as to see the most reviewed sauces.
The actual goal of the project is not stated in the proposal, saying what actually the dataset will reveal for both the questions. It is mentioned that the data was chosen with it being convenient (feature-wise and information-wise)

- Describe the data used or collected.

The data collected contains three sub sets.
The first set gives information about number of episodes per season, the guests on the show and their total appearances and if they finished trying all sauces. The other two sets describe the types of sauces and their Scoville value. The third set gives information related to season and episode number

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The first question demands a correlating graph, for which the team is using Scatter Plot. There are 2 datasets used as a source, giving avg_score and unfinished_score.
The second question demands for a frequency plot to compare the sauce frequency in each series/season? (unclear). This will be demonstrated with a sunburst plot.

- Is there anything that is unclear from the proposal?

1.  The questions and the answers plan are not discrete and they are mixed up.
2.  The team has not phrased the analysis plan for the first question clearly. 
3.  Goal given is unclear as the team has mentioned why they like the dataset but not what is derived from the data.
4.  It is not clear whether the team is trying to plot for just season and sauce or the entire series? 
5. It is unclear whether the average Scoville is for the sauce or the season based on how the question is phrased. 

- Provide constructive feedback on how the team might be able to improve their project.

1. Remove the sub sections from the question and add it to the analysis section.
2. Team should be concise in their explanation. 
3. The data description is well done but the overall information analysis (goal) of the data is not mentioned anywhere.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We will be interested to know if the second plot will reveal anything about the preference or popularity of the sauce.

- Provide constructive feedback on any issues with file and/or code organization.

None

- (Optional) Any further comments or feedback?

1. The team could provide a backup analysis plan if the visualization does not turn out the way they want.

**Comment by datalyticsintel** [comment]
Thank you for the feedback. We considered much of it and made improvements to our explanation and analysis. We even switched out a question.
