### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by SwethaSiripurapuu** [INFO526-DataViz/project-01-ScatterPlot-Sorcerers#2]
The following is the peer review of the project proposal by ggplotGurus. The team members that participated in this review are 

- Swetha Siripurapu - @SwethaSiripurapuu 
- Shalon Walter - @shalonwalter
- Deema - @Deec0dez 
- Kiwoon Hong- @KiwoonHong 
- Harshit Mehra - @harshitmehra1 

- Describe the goal of the project.

They are trying to analyze the different kinds of sauces used in the show.   

- Describe the data used or collected.

The dataset has three sets of data: the first one is about the information about the episodes and contains 8 variables and 300 observations. The second dataset set contains the data related to the sauces. It has 4 variables and 210 observations. The Third data set contains the data related to seasons and contains 5 variables and 21 observations.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The first question is quite interesting, and they are trying to find the season which has the most unfinished contestants. For the second question they plan on extracting the data of the sauces that appeared more than once in the series and plot a sunburst chart to visualize which season have a greater number of repetitive sauces.

- Is there anything that is unclear from the proposal?
we are not clear about what the second question is about? if they can give us more details on how they are trying to solve will clear some air.

- Provide constructive feedback on how the team might be able to improve their project.

There is a general concern about the second question. They are trying to find the season that had repeated use of sauces. Due to the nature of the show, each season does repeat its sauces. Therefore, there might not be a statistically significant value of p<0.05

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We are excited to see if there any correlation between the scoville score of the sauce and the number of guests who did not finish trying all the sauces. 

- Provide constructive feedback on any issues with file and/or code organization.

Sunburst charts are not the best way to show ranking in data. 

- (Optional) Any further comments or feedback?

**Comment by datalyticsintel** [comment]
Thank you for the feedback. We took a lot of it under consideration and made improvements on our explanation and analysis. We even switched out a question.
