### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by KiwoonHong** [INFO526-DataViz/project-01-ScatterPlot-Sorcerers#4]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

- [Swetha Siripurapu] - @[SwethaSiripurapuu]
- [Shalon Walter] - @[shalonwalter]
- [Deema] - @[Deec0dez]
- [Kiwoon Hong]- @[KiwoonHong]
- [Harshit Mehra] - @[harshitmehra1]

- Content: Is the research question well designed and is the data being used relevant to the research question?

The team provided an intuitive and easy visualization of the questions, so we could see the analysis of the questions directly in the plot. the combined bar and line plot effectively shows the relationship between Scoville score and unfinished contestants by season. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

the horizontal bar plot clearly illustrates the frequency of repeated sauces across seasons. Both visualizations are appropriate for the data presented.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

The "ScatterPlot-Sorcerers" team's project, "From Mild to Wild," presents an insightful examination of the YouTube series "Hot Ones" with a focus on sauce Scoville scores and contestant failure rates. Their approach is systematic and thorough, leveraging multiple datasets to explore their two areas of interest. Their visual representation, which effectively combines histograms and smoothed plots, suggests that they've carefully considered how to best present their findings. Additionally, they have put significant thought into the design of their visualizations, with the use of color gradients and text annotations enhancing the clarity of the data. Their conclusion highlights the balancing act the show maintains between introducing new spicy challenges and retaining sauces that resonate with viewers. It's evident that substantial effort and strategic planning went into the project's execution.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

Their slides are actually amazing. They start with a creative title, "From Mild to Wild" with a dark picture of the show in the background, aligning with the dark theme of the slides. The presentation is full of funny pictures and gifs, and their figures are solid. The transition between slides is also great. From start to end, there is not a single boring slide in their presentation. Well Done!

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

They were confident and spoke loudly, so you could tell their message was clear in their presentation. Also, their project seemed to be fairly distributed.

**Comment by Gchism94** [comment]
Based on the feedback, the peer review score is 5/5
